sfputil and sfpshow eeprom and DOM CLI enhancement to display data for all CMIS transceivers (#4017)
<!--
 Please make sure you've read and understood our contributing guidelines:
 https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

 failure_prs.log skip_prs.log Make sure all your commits include a signature generated with `git commit -s` **

 If this is a bug fix, make sure your description includes "closes #xxxx",
 "fixes #xxxx" or "resolves #xxxx" so that GitHub automatically closes the related
 issue when the PR is merged.

 If you are adding/modifying/removing any command or utility script, please also
 make sure to add/modify/remove any unit tests from the tests
 directory as appropriate.

 If you are modifying or removing an existing 'show', 'config' or 'sonic-clear'
 subcommand, or you are adding a new subcommand, please make sure you also
 update the Command Line Reference Guide (doc/Command-Reference.md) to reflect
 your changes.

 Please provide the following information:
-->

#### What I did
This PR enhances the sfputil and sfpshow CLI tools to properly display EEPROM and DOM data for all CMIS-compliant transceivers, not just QSFP-DD and OSFP modules. The enhancement replaces hardcoded transceiver type checks with a more generic detection method based on the presence of the cmis_rev field in transceiver information.
https://github.com/sonic-net/sonic-utilities/blob/252a643567dda88ddf93a72508e0331cdd7cb677/sfputil/main.py#L340
https://github.com/sonic-net/sonic-utilities/blob/252a643567dda88ddf93a72508e0331cdd7cb677/sfputil/main.py#L396
https://github.com/sonic-net/sonic-utilities/blob/252a643567dda88ddf93a72508e0331cdd7cb677/sfputil/main.py#L414

Currently, the transceivers which have identifier register value as 0x1e (`QSFP+ or later with CMIS`) show EEPROM and DOM output for non-CMIS transceivers.

Also, fixes the below crash seen on Backplane cartridge
```
root@str5-7060x6-moby-512-4:/home/admin# sfputil show eeprom -p Ethernet128
Traceback (most recent call last):
 File "/usr/local/bin/sfputil", line 8, in <module>
 sys.exit(cli())
 ^^^^^
 File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 764, in __call__
 return self.main(*args, **kwargs)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 717, in main
 rv = self.invoke(ctx)
 ^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1137, in invoke
 return _process_result(sub_ctx.command.invoke(sub_ctx))
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1137, in invoke
 return _process_result(sub_ctx.command.invoke(sub_ctx))
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 956, in invoke
 return ctx.invoke(self.callback, **ctx.params)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 555, in invoke
 return callback(*args, **kwargs)
 ^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/sfputil/main.py", line 685, in eeprom
 output += convert_sfp_info_to_output_string(xcvr_info)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/sfputil/main.py", line 382, in convert_sfp_info_to_output_string
 output += '{}{}: {}\n'.format(indent, QSFP_DATA_MAP[key], sfp_info_dict[key])
 ~~~~~~~~~~~~~^^^^^
KeyError: 'connector'
```
#### How I did it
- Introduced a new helper function is_transceiver_cmis() to identify CMIS-compliant transceivers
- Modified DOM and EEPROM display logic to use CMIS detection instead of specific type checking
- Updated test data and expected outputs to reflect enhanced CMIS field display

sfputil Backplane Cartridge crash fix details
- The current crash was seen due to the sfputil CLI handler looking for `connector` field and this field was absent from the sfp_info_dict.
- Also, the backplane cartridge was treaterd as non CMIS optic. With the current fix, backplane catridge is now treated as a CMIS optic (due to the presence of `cmis_rev` field) and the crash due to the absence of connector field is not seen any more due to the already existing graceful handling of KeyError for CMIS optics (https://github.com/sonic-net/sonic-utilities/blob/c0838d7f6cabdc42079aea638706eed76567d75b/sfputil/main.py#L360-L361) unlike non-CMIS optics handling (https://github.com/sonic-net/sonic-utilities/blob/c0838d7f6cabdc42079aea638706eed76567d75b/sfputil/main.py#L382)

#### How to verify it
Ensured the CLI output shows all CMIS relevant fields for the transceiver with 0x1e in the identifier value.

sfpshow output change
- The DOM EEPROM dump CLI will show DOM data for lanes 5 through 8 too now (irrespective of it being used or not)
- Threshold data will be shown for TxPower thresholds

sfputil output change
- The EEPROM CLI will display data inline to other QSFP-DD and OSFP CMIS modules (example - Active application lane, CMIS revision etc)
- The DOM EEPROM dump CLI will show DOM data for lanes 5 through 8 too now (irrespective of it being used or not)
- Threshold data will be shown for TxPower thresholds

#### Previous command output (if the output of a command-line utility has changed)
```
sfputil show eeprom -d -p Ethernet96
Ethernet96: SFP EEPROM detected
 Application Advertisement: {1: {'host_electrical_interface_id': '200GAUI-4 C2M (Annex 120E)', 'module_media_interface_id': 'Active Cable assembly with BER < 2.6x10^-4', 'media_lane_count': 4, 'host_lane_count': 4, 'host_lane_assignment_options': 1, 'media_lane_assignment_options': 1}, 2: {'host_electrical_interface_id': 'CAUI-4 C2M (Annex 83E) without FEC', 'module_media_interface_id': 'Active Cable assembly with BER < 5x10^-5', 'media_lane_count': 4, 'host_lane_count': 4, 'host_lane_assignment_options': 1, 'media_lane_assignment_options': 1}}
 Connector: No separable connector
 Encoding: N/A
 Extended Identifier: Power Class 3 (3.75W Max)
 Extended RateSelect Compliance: N/A
 Identifier: QSFP+ or later with CMIS
 Length Cable Assembly(m): 14.0
 Nominal Bit Rate(100Mbs): N/A
 Specification compliance:
 N/A
 Vendor Date Code(YYYY-MM-DD Lot): 2025-01-24
 Vendor Name: VENDOR_NAME_ABC
 Vendor OUI: 00-90-65
 Vendor PN: VENDOR_PN_A123456
 Vendor Rev: A0
 Vendor SN: SN12345
 ChannelMonitorValues:
 RX1Power: -0.818dBm
 RX2Power: -0.738dBm
 RX3Power: -0.46dBm
 RX4Power: -0.402dBm
 TX1Bias: 7.504mA
 TX1Power: -4.559dBm
 TX2Bias: 7.504mA
 TX2Power: -4.559dBm
 TX3Bias: 7.504mA
 TX3Power: -4.559dBm
 TX4Bias: 7.504mA
 TX4Power: -4.559dBm
 ChannelThresholdValues:
 RxPowerHighAlarm : 5.0dBm
 RxPowerHighWarning: 4.0dBm
 RxPowerLowAlarm : -14.001dBm
 RxPowerLowWarning : -11.002dBm
 TxBiasHighAlarm : 13.0mA
 TxBiasHighWarning : 11.0mA
 TxBiasLowAlarm : 3.0mA
 TxBiasLowWarning : 5.0mA
 ModuleMonitorValues:
 Temperature: 27.457C
 Vcc: 3.283Volts
 ModuleThresholdValues:
 TempHighAlarm : 75.0C
 TempHighWarning: 70.0C
 TempLowAlarm : -5.0C
 TempLowWarning : 0.0C
 VccHighAlarm : 3.465Volts
 VccHighWarning : 3.45Volts
 VccLowAlarm : 3.135Volts
 VccLowWarning : 3.15Volts
```
#### New command output (if the output of a command-line utility has changed)
```
sfputil show eeprom -d -p Ethernet96
Ethernet96: SFP EEPROM detected
 Active App Selection Host Lane 1: 1
 Active App Selection Host Lane 2: 1
 Active App Selection Host Lane 3: 1
 Active App Selection Host Lane 4: 1
 Active App Selection Host Lane 5: 0
 Active App Selection Host Lane 6: 0
 Active App Selection Host Lane 7: 0
 Active App Selection Host Lane 8: 0
 Application Advertisement: 200GAUI-4 C2M (Annex 120E) - Host Assign (0x1) - Active Cable assembly with BER < 2.6x10^-4 - Media Assign (0x1)
 CAUI-4 C2M (Annex 83E) without FEC - Host Assign (0x1) - Active Cable assembly with BER < 5x10^-5 - Media Assign (0x1)
 CMIS Revision: 5.1
 Connector: No separable connector
 Encoding: N/A
 Extended Identifier: Power Class 3 (3.75W Max)
 Extended RateSelect Compliance: N/A
 Hardware Revision: 1.0
 Host Electrical Interface: 200GAUI-4 C2M (Annex 120E)
 Host Lane Assignment Options: 1
 Host Lane Count: 4
 Identifier: QSFP+ or later with CMIS
 Length Cable Assembly(m): 14.0
 Media Interface Code: Active Cable assembly with BER < 2.6x10^-4
 Media Interface Technology: 850 nm VCSEL
 Media Lane Assignment Options: 1
 Media Lane Count: 4
 Nominal Bit Rate(100Mbs): N/A
 Specification compliance: active_cable_media_interface
 Vendor Date Code(YYYY-MM-DD Lot): 2025-01-24
 Vendor Name: VENDOR_NAME_ABC
 Vendor OUI: 00-90-65
 Vendor PN: VENDOR_PN_A123456
 Vendor Rev: A0
 Vendor SN: SN12345
 ChannelMonitorValues:
 RX1Power: -0.799dBm
 RX2Power: -0.738dBm
 RX3Power: -0.46dBm
 RX4Power: -0.402dBm
 RX5Power: -infdBm
 RX6Power: -infdBm
 RX7Power: -infdBm
 RX8Power: -infdBm
 TX1Bias: 7.504mA
 TX1Power: -4.559dBm
 TX2Bias: 7.504mA
 TX2Power: -4.559dBm
 TX3Bias: 7.504mA
 TX3Power: -4.559dBm
 TX4Bias: 7.504mA
 TX4Power: -4.559dBm
 TX5Bias: 0.0mA
 TX5Power: -infdBm
 TX6Bias: 0.0mA
 TX6Power: -infdBm
 TX7Bias: 0.0mA
 TX7Power: -infdBm
 TX8Bias: 0.0mA
 TX8Power: -infdBm
 ChannelThresholdValues:
 RxPowerHighAlarm : 5.0dBm
 RxPowerHighWarning: 4.0dBm
 RxPowerLowAlarm : -14.001dBm
 RxPowerLowWarning : -11.002dBm
 TxBiasHighAlarm : 13.0mA
 TxBiasHighWarning : 11.0mA
 TxBiasLowAlarm : 3.0mA
 TxBiasLowWarning : 5.0mA
 TxPowerHighAlarm : 5.0dBm
 TxPowerHighWarning: 3.0dBm
 TxPowerLowAlarm : -10.0dBm
 TxPowerLowWarning : -8.0dBm
 ModuleMonitorValues:
 Temperature: 27.977C
 Vcc: 3.282Volts
 ModuleThresholdValues:
 TempHighAlarm : 75.0C
 TempHighWarning: 70.0C
 TempLowAlarm : -5.0C
 TempLowWarning : 0.0C
 VccHighAlarm : 3.465Volts
 VccHighWarning : 3.45Volts
 VccLowAlarm : 3.135Volts
 VccLowWarning : 3.15Volts
```

ADO - 34032819