Exclude Smart Switch from modular chassis operations/checks (#4008)
<!--
 Please make sure you've read and understood our contributing guidelines:
 https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

 failure_prs.log skip_prs.log Make sure all your commits include a signature generated with `git commit -s` **

 If this is a bug fix, make sure your description includes "closes #xxxx",
 "fixes #xxxx" or "resolves #xxxx" so that GitHub automatically closes the related
 issue when the PR is merged.

 If you are adding/modifying/removing any command or utility script, please also
 make sure to add/modify/remove any unit tests from the tests
 directory as appropriate.

 If you are modifying or removing an existing 'show', 'config' or 'sonic-clear'
 subcommand, or you are adding a new subcommand, please make sure you also
 update the Command Line Reference Guide (doc/Command-Reference.md) to reflect
 your changes.

 Please provide the following information:
-->
#### Why I did it
When running the `test_fwutil_update_current` test in https://github.com/sonic-net/sonic-mgmt/blob/master/tests/platform_tests/fwutil/test_fwutil.py we encounter the following issue when we run the command
```
admin@sonic:$ sudo fwutil update chassis component ONIE fw -y

Error: Failed to parse "platform_components.json": invalid platform schema: "module" key hasn't been found. Aborting...

Aborted!
```
This is because platform_components.json for smartswitch doesn't have module key in it and this should be ignored for smartswitch.

#### What I did
Avoid any modular chassis operations on smart-switch.

#### How I did it
Added a check to verify the device is not a smart switch before treating it as a modular chassis.