Add namespace support for show interface neighbor expected (#3790)
<!--
 Please make sure you've read and understood our contributing guidelines:
 https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

 failure_prs.log Make sure all your commits include a signature generated with `git commit -s` **

 If this is a bug fix, make sure your description includes "closes #xxxx",
 "fixes #xxxx" or "resolves #xxxx" so that GitHub automatically closes the related
 issue when the PR is merged.

 If you are adding/modifying/removing any command or utility script, please also
 make sure to add/modify/remove any unit tests from the tests
 directory as appropriate.

 If you are modifying or removing an existing 'show', 'config' or 'sonic-clear'
 subcommand, or you are adding a new subcommand, please make sure you also
 update the Command Line Reference Guide (doc/Command-Reference.md) to reflect
 your changes.

 Please provide the following information:
-->

#### What I did

Adding namespace support for `show interface neighbor expected`. So that we can use

```
show interface neighbor expected -n asic0
```

#### How I did it

#### How to verify it
Verified on T2 testbed

#### Previous command output (if the output of a command-line utility has changed)
```
admin@somehost:/var/log$ show interfaces neighbor expected -n asic1
Usage: show interfaces neighbor expected [OPTIONS] [INTERFACENAME]
Try "show interfaces neighbor expected -h" for help.

Error: no such option: -n
```

#### New command output (if the output of a command-line utility has changed)
```
admin@somehost:/var/log$ show interfaces neighbor expected -n asic1
LocalPort Neighbor NeighborPort NeighborLoopback NeighborMgmt NeighborType
----------- ---------- -------------- ------------------ -------------- --------------
Ethernet96 ARISTAXXTX Ethernet1 None XXX.XX.XXX.XX someHub
Ethernet104 ARISTAXXTX Ethernet1 None XXX.XX.XXX.XX otherHub
...
```