[multi-asic] Fix the 'config reload' flow in case when multiple golden_config.json files provided (#3927)
<!--
 Please make sure you've read and understood our contributing guidelines:
 https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

 failure_prs.log skip_prs.log Make sure all your commits include a signature generated with `git commit -s` **

 If this is a bug fix, make sure your description includes "closes #xxxx",
 "fixes #xxxx" or "resolves #xxxx" so that GitHub automatically closes the related
 issue when the PR is merged.

 If you are adding/modifying/removing any command or utility script, please also
 make sure to add/modify/remove any unit tests from the tests
 directory as appropriate.

 If you are modifying or removing an existing 'show', 'config' or 'sonic-clear'
 subcommand, or you are adding a new subcommand, please make sure you also
 update the Command Line Reference Guide (doc/Command-Reference.md) to reflect
 your changes.

 Please provide the following information:
-->

#### What I did
Fix the issue introduced by [Enable config reload yang validation for multiasic #3825](https://github.com/sonic-net/sonic-utilities/pull/3825).
Fix the `config reload` flow in case when multiple `golden_config.json` files provided.

#### How I did it
Add check for multi-asic.

#### How to verify it
Manual verification by running the:
```
cisco@sonic-lc5:~$ sudo config reload -y -f -l /etc/sonic/running_golden_config.json,/etc/sonic/running_golden_config0.json,/etc/sonic/running_golden_config1.json,/etc/sonic/running_golden_config2.json
```
Run the whole sonic-utilities UT suite.

#### Previous command output (if the output of a command-line utility has changed)
```
cisco@sonic-lc5:~$ sudo config reload -y -f -l /etc/sonic/running_golden_config.json,/etc/sonic/running_golden_config0.json,/etc/sonic/running_golden_config1.json,/etc/sonic/running_golden_config2.json
Acquired lock on /etc/sonic/reload.lock
Released lock on /etc/sonic/reload.lock
Traceback (most recent call last):
 File "/usr/local/lib/python3.11/dist-packages/config/main.py", line 158, in read_json_file
 with open(fileName) as f:
 ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/etc/sonic/running_golden_config.json,/etc/sonic/running_golden_config0.json,/etc/sonic/running_golden_config1.json,/etc/sonic/running_golden_config2.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/usr/local/bin/config", line 8, in <module>
 sys.exit(config())
 ^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 764, in __call__
 return self.main(*args, **kwargs)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 717, in main
 rv = self.invoke(ctx)
 ^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1137, in invoke
 return _process_result(sub_ctx.command.invoke(sub_ctx))
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 956, in invoke
 return ctx.invoke(self.callback, **ctx.params)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 555, in invoke
 return callback(*args, **kwargs)
 ^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/click/decorators.py", line 64, in new_func
 return ctx.invoke(f, obj, *args, **kwargs)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 555, in invoke
 return callback(*args, **kwargs)
 ^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/utilities_common/flock.py", line 71, in _wrapper
 return func(*args, **kwargs)
 ^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/config/main.py", line 1884, in reload
 config_file_yang_validation(filename)
 File "/usr/local/lib/python3.11/dist-packages/config/main.py", line 1410, in config_file_yang_validation
 config = read_json_file(filename)
 ^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/config/main.py", line 161, in read_json_file
 raise Exception(str(e))
Exception: [Errno 2] No such file or directory: '/etc/sonic/running_golden_config.json,/etc/sonic/running_golden_config0.json,/etc/sonic/running_golden_config1.json,/etc/sonic/running_golden_config2.json'
```

#### New command output (if the output of a command-line utility has changed)
```
cisco@sonic-lc5:~$ sudo config reload -y -f -l /etc/sonic/running_golden_config.json,/etc/sonic/running_golden_config0.json,/etc/sonic/running_golden_config1.json,/etc/sonic/running_golden_config2.json
Acquired lock on /etc/sonic/reload.lock
Disabling container and routeCheck monitoring ...
Stopping SONiC target ...
Running command: /usr/local/bin/sonic-cfggen -H -k Cisco-88-LC0-36FH-M-O36 --write-to-db
Running command: /usr/local/bin/sonic-cfggen -j /etc/sonic/init_cfg.json -j /etc/sonic/running_golden_config.json --write-to-db
Running command: /usr/local/bin/db_migrator.py -o migrate
Running command: /usr/local/bin/sonic-cfggen -H -k Cisco-88-LC0-36FH-M-O36 -n asic0 --write-to-db
Warning: Failed to get device ID from asic.conf file for asic0
Running command: /usr/local/bin/sonic-cfggen -j /etc/sonic/init_cfg.json -j /etc/sonic/running_golden_config0.json -n asic0 --write-to-db
Running command: /usr/local/bin/db_migrator.py -o migrate -n asic0
Running command: /usr/local/bin/sonic-cfggen -H -k Cisco-88-LC0-36FH-M-O36 -n asic1 --write-to-db
Warning: Failed to get device ID from asic.conf file for asic1
Running command: /usr/local/bin/sonic-cfggen -j /etc/sonic/init_cfg.json -j /etc/sonic/running_golden_config1.json -n asic1 --write-to-db
Running command: /usr/local/bin/db_migrator.py -o migrate -n asic1
Running command: /usr/local/bin/sonic-cfggen -H -k Cisco-88-LC0-36FH-M-O36 -n asic2 --write-to-db
Warning: Failed to get device ID from asic.conf file for asic2
Running command: /usr/local/bin/sonic-cfggen -j /etc/sonic/init_cfg.json -j /etc/sonic/running_golden_config2.json -n asic2 --write-to-db
Running command: /usr/local/bin/db_migrator.py -o migrate -n asic2
Running command: /usr/local/bin/sonic-cfggen -d -y /etc/sonic/sonic_version.yml -t /usr/share/sonic/templates/sonic-environment.j2,/etc/sonic/sonic-environment
Restarting SONiC target ...
Enabling container and routeCheck monitoring ...
Reloading Monit configuration ...
Reinitializing monit daemon
Released lock on /etc/sonic/reload.lock
```